### ISSUE TITLE
Wuffs-using code could use C++ convenience methods

### ISSUE THREAD

**Issue by nigeltao** [glaretechnologies/glare-core#1]
`graphics/PNGDecoder.cpp` uses the third-party Wuffs library. Wuffs is first and foremost a C library (and C doesn't have namespaces or methods, so the function names are long and the `this`-equivalent is explicitly passed as the first argument), but it also has some C++ methods that can simplify some of the `PNGDecoder.cpp` code. For example:

---

```
wuffs_png__decoder png_decoder;
wuffs_base__status status = wuffs_png__decoder__initialize(&png_decoder, sizeof(png_decoder), etc, etc);
wuffs_png__decoder__set_quirk_enabled(&png_decoder, WUFFS_BASE__QUIRK_IGNORE_CHECKSUM, true);
```

can become

```
wuffs_png__decoder png_decoder;
wuffs_base__status status = png_decoder.initialize(sizeof(png_decoder), etc, etc);
png_decoder.set_quirk_enabled(WUFFS_BASE__QUIRK_IGNORE_CHECKSUM, true);
```

---

```
const wuffs_base__pixel_format pixel_format = wuffs_base__pixel_config__pixel_format(&image_config.pixcfg);
const uint32_t w = wuffs_base__pixel_config__width(&image_config.pixcfg);
const uint32_t h = wuffs_base__pixel_config__height(&image_config.pixcfg);
```

can become

```
const wuffs_base__pixel_format pixel_format = image_config.pixcfg.pixel_format();
const uint32_t w = image_config.pixcfg.width();
const uint32_t h = image_config.pixcfg.height();
```

---

And so on.

**Comment by nigeltao** [comment]
Also,

```
wuffs_base__io_buffer src_io_buffer = wuffs_base__make_io_buffer(
  wuffs_base__make_slice_u8((uint8*)buffer_view_in_stream.currentReadPtr(), effective_buf_size),
  wuffs_base__make_io_buffer_meta(/*write index=*/effective_buf_size, /*read index=*/0, /*pos=*/effective_buf_size, /*closed=*/true)
);
```

could instead be

```
wuffs_base__io_buffer src_io_buffer = wuffs_base__ptr_u8__reader(
  (uint8*)buffer_view_in_stream.currentReadPtr(),
  effective_buf_size,
  /*closed=*/true
);
```

which also fixes the bug where you're passing `/*pos=*/effective_buf_size` instead of `/*pos=*/0`. The `pos` is supposed to be the stream position of `&src_io_buffer.data.ptr[0]`, not `&src_io_buffer.data.ptr[ri]` or `&src_io_buffer.data.ptr[wi]`, where `ri` and `wi` are short names for the read-index and write-index metadata fields: `src_io_buffer.meta.ri` and `src_io_buffer.meta.wi`. It's actually impossible (in general) for the `pos` argument to equal both the "read position" and "write position" *at the same time*, since they may be different positions (and a Wuffs I/O buffer, like a Unix pipe, has both a read-side and a write-side).

This bug is largely harmless, though. The `buf.meta.pos` (and its derived `buf.reader_position()`, which basically just returns `pos + ri`) is mostly used for animated images (e.g. animated GIFs) specifically when you want to e.g. rewind to frame 123 (at byte position 45678) and replay from there onwards. For glare-core, if you're decoding a static (not animated) PNG as a one-shot operation, it's not going to matter.

Wuffs documentation could admittedly be better about this, although there is [this animation](https://nigeltao.github.io/blog/2020/jsonptr-readers-writers-compactions.gif) (note how `buf.meta.pos` starts at zero, not the length of the data), from [a separate blog post](https://nigeltao.github.io/blog/2020/jsonptr.html).

**Comment by Ono-Sendai** [comment]
Thanks for reports, will fix.

**Comment by Ono-Sendai** [comment]
Fixed in https://github.com/glaretechnologies/glare-core/commit/ff29e76fee4ca46875d7f913b6d0ceff40cb44ee and https://github.com/glaretechnologies/glare-core/commit/6daf59c00a316abcc42ae7db7ae642a2239dce14, thank you.
